apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: merge-sort-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Rohan6395/Advance_Sorting.git'
    targetRevision: HEAD
    path: manifests  # Folder containing your yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
